Feature/email submit 1
double-espresso/miscellaneous pull request #1
Opened 2017-09-19 17:02 UTC by sinyru

2017-09-19 17:07 UTC, sinyru commented
I am able to get email submission from users on slack, but I am getting the following error.

Error: {error: SyntaxError: Unexpected token o in JSON at position 0 at Object.parse (<anonymous>) at XMLHt…, text: "ok"}

2017-09-22 12:48 UTC, GiorgioNatili requested changes

2017-09-22 12:48 UTC, GiorgioNatili commented on src/app/app.component.ts
> +
Don't remove the title, let's call it `SwiftFest Slack Channel`

2017-09-22 12:48 UTC, GiorgioNatili commented on src/app/app.module.ts
> +
extra empty line

2017-09-22 12:48 UTC, GiorgioNatili commented on src/app/landing-page/landing-page.component.html
> +<input type="text" [(ngModel)]="emailInput">
I don't like too much bi-directional data binding, why are you using it?

2017-09-22 12:48 UTC, GiorgioNatili commented on src/app/landing-page/landing-page.component.html
> +  submit email
In a separate PR please integrate https://github.com/ngx-translate/core to store labels outside of the code base.

2017-09-22 12:48 UTC, GiorgioNatili commented on src/app/landing-page/landing-page.component.ts
> +  ngOnInit() {
Remove it if not needed

2017-10-03 20:25 UTC, merged